# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jimmynotjim
email: jimmynotjim@me.com
description: > # this means to ignore newlines until "baseurl:"
  A home builder turned web maker and image taker. Raised in small town
  New England, currently lost somewhere on the prairie.
twitter_username: jimmynotjim
github_username:  jimmynotjim
permalink: pretty
collections:
  writing:
    output: true,
    permalink: /:collection/:path/
  store:
    output: true,
    permalink: /:collection/:path/

typekit_code: fxk6cse
ga_code:      UA-15192663-6

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .eslintrc
  - .gitignore
  - .npmrc
  - node_modules
  - src
  - gulp
  - gulpfile.js
  - package.json
  - npm-debug.log
  - setup.sh
  - CHANGELOG.md
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - TERMS.md
